height: "500"
toolbar:
  - undo redo | formatselect | link | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help
plugins:
  - advlist autolink lists link image charmap print preview anchor
  - searchreplace visualblocks code fullscreen
  - insertdatetime media table paste code help wordcount
